### ISSUE TITLE
Roadmap:

### ISSUE THREAD

**Issue by frank-dspeed** [frank-dspeed/component-manager-ui#1]
We want to integrate via the following main Integration Points into existing Operating systems:

## Task Schedulers
as the core principles of our stealify fundamentals introduce tasks as one of our core components it is more then reasonable that we choose the following

- [ ] MacOS Ventura Automator
- [ ] Existing electron deployments
- [ ] Existing nwjs deployments
- [ ] Existing nodejs deployments
- [ ] A Manual that shows how to enable Task Scheduling on all existing Platforms and OS
- [ ] cron
- [ ] systemd
- [ ] launchd
- [ ] libcontainer
